# Generated by Django 4.0 on 2021-12-22 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItalianiCH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64, null=True)),
                ('cognome', models.CharField(blank=True, max_length=64, null=True)),
                ('data_di_nascita', models.CharField(blank=True, max_length=64, null=True)),
                ('sesso', models.CharField(blank=True, max_length=64, null=True)),
                ('campo_citta', models.CharField(blank=True, max_length=64, null=True)),
                ('codice', models.CharField(blank=True, max_length=64, null=True)),
                ('consolato', models.CharField(blank=True, max_length=64, null=True)),
                ('consolato_citta', models.IntegerField(blank=True, null=True)),
                ('cap', models.CharField(blank=True, max_length=64, null=True)),
                ('indirizzo', models.CharField(blank=True, max_length=64, null=True)),
                ('citta', models.CharField(blank=True, max_length=64, null=True)),
                ('sigla', models.CharField(blank=True, max_length=64, null=True)),
                ('lan', models.CharField(blank=True, max_length=64, null=True)),
                ('lng', models.CharField(blank=True, max_length=64, null=True)),
                ('Nazione', models.CharField(blank=True, max_length=64, null=True)),
                ('slug', models.CharField(blank=True, max_length=64, null=True)),
                ('distretto', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
