# Generated by Django 4.0 on 2021-12-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('italiani', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='italianich',
            name='consolato_citta',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
